# Generated by Django 3.2.5 on 2022-09-23 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Dr', 'Dr'), ('MDDr', 'MDDr'), ('MUDr', 'MUDr'), ('Bc', 'Bc'), ('Mrs', 'Mrs'), ('Mr', 'Mr')], max_length=20)),
                ('fname', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('field', models.CharField(choices=[('Dental Surgery', 'Dental Surgery'), ('Stomatology', 'Stomatology'), ('Implantology', 'Implantology'), ('Dental Hygiene', 'Dental Hygiene'), ('Administrator', 'Administrator')], default=0, max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('insurance_c', models.CharField(choices=[('GHI', 'GHI'), ('Confidence', 'Confidence'), ('Union', 'Union')], max_length=20)),
                ('cell_phone_num', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dent.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dent.patient')),
            ],
        ),
    ]
